[project]
name = "pyfonts"
version = "1.2.0"
description = "A simple and reproducible way of using fonts in matplotlib"
readme = "README.md"
requires-python = ">=3.9"
license = "MIT"
license-files = ["LICENSE"]
authors = [
  { name = "Joseph Barbier", email = "joseph.barbierdarnal@gmail.com" },
]
keywords = ["bunny", "font", "google", "matplotlib", "reproducibility"]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Framework :: Matplotlib",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3"
]
dependencies = [
  "matplotlib",
  "requests",
]

[project.urls]
Documentation = "https://y-sunflower.github.io/pyfonts/"
Homepage = "https://y-sunflower.github.io/pyfonts/"
Issues = "https://github.com/y-sunflower/pyfonts/issues"
Repository = "https://github.com/y-sunflower/pyfonts"

[dependency-groups]
dev = [
  "coverage>=7.9.1",
  "genbadge[coverage]>=1.1.2",
  "mkdocs-material>=9.6.9",
  "mkdocs-matplotlib>=0.10.1",
  "mkdocs-redirects>=1.2.2",
  "mkdocstrings-python>=1.16.5",
  "prek>=0.3.5",
  "pytest>=8.3.5",
  "ty==0.0.20",
]

[build-system]
requires = [
  "setuptools",
  "setuptools-scm",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pyfonts"]

[tool.ty.src]
exclude = ["tests"]

[tool.uv.sources]
pyfonts = { workspace = true }
